APP_NOT_FOUND = "App not found"
CHECKSUM_MISMATCH = "Unauthorized access: checksum mismatch"
NO_CHECKSUM = "Unauthorized access: no checksum"
SCORENAME_NOT_FOUND = "Score name not found"
USER_ALREADY_REGISTERED = "User already registered"
